import { Router } from 'express';
import authRoutes from './auth';
import userRoutes from './users';
import categoryRoutes from './categories';
import productRoutes from './products';
import floorRoutes from './floors';
import customerRoutes from './customers';
import couponRoutes from './coupons';
import promotionRoutes from './promotions';
import paymentMethodRoutes from './paymentMethods';
import sessionRoutes from './sessions';
import orderRoutes from './orders';
import reportRoutes from './reports';
import receiptEmailRoutes from './receiptEmail';
import publicRoutes from './public';
import inventoryRoutes from './inventory';
import supplierRoutes from './suppliers';
import purchaseOrderRoutes, { grnRouter } from './purchaseOrders';
import recipeRoutes from './recipes';
import wastageRoutes from './wastage';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/floors', floorRoutes);
router.use('/customers', customerRoutes);
router.use('/coupons', couponRoutes);
router.use('/promotions', promotionRoutes);
router.use('/payment-methods', paymentMethodRoutes);
router.use('/sessions', sessionRoutes);
router.use('/orders', orderRoutes);
router.use('/reports', reportRoutes);
router.use('/receipt-email', receiptEmailRoutes);
router.use('/public', publicRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/grn', grnRouter);
router.use('/recipes', recipeRoutes);
router.use('/wastage', wastageRoutes);

export default router;
